<project name="goobi-plugin-workflow-massupload" default="devbuild">
	<target name="devbuild">
		<exec executable="mvn">
			<arg value="package"/>
            <arg value="-Dmaven.test.skip=true" />
		</exec>
        <copy file="module-base/target/plugin-workflow-mass-upload-base.jar" todir="/opt/digiverso/goobi/plugins/workflow/" overwrite="true"/>
        <copy file="module-gui/target/plugin-workflow-mass-upload-gui.jar" todir="/opt/digiverso/goobi/plugins/GUI/" overwrite="true"/>

	</target>
</project>
